### ISSUE TITLE
The translation of dash to dock is not complete.

### ISSUE THREAD

**Issue by laichiaheng** [micheleg/dash-to-dock#1009]
How to translate it?

**Comment by pyroxar** [comment]
https://micheleg.github.io/dash-to-dock/localization.html

I will help you if you need more information.

**Comment by laichiaheng** [comment]
@micheleg @pyroxar Would you update the translation?
[zh_TW.zip](https://github.com/micheleg/dash-to-dock/files/3706805/zh_TW.zip)
However, I still can't find the "Trash" or "Empty Trash" in the po file.

**Comment by pyroxar** [comment]
@laichiaheng did you generate new pot file and then update your po file?

**Comment by pyroxar** [comment]
1 Fork this repo:
![obraz](https://user-images.githubusercontent.com/23406555/66489514-0923de00-eab0-11e9-88ac-e4d09b712cca.png)

2 Clone to your computer **from your repository** - git clone ...
![obraz](https://user-images.githubusercontent.com/23406555/66489796-759edd00-eab0-11e9-8acf-e4ed3bf467a1.png)

3 Go to cloned folder and:
3.1 create new branch
3.2 switch to new branch
Now you cane make changes (it is very good practice for you, when you do something new = new branch)
![obraz](https://user-images.githubusercontent.com/23406555/66490355-4e94db00-eab1-11e9-981f-c7752bdc664a.png)

4 make potfile (https://micheleg.github.io/dash-to-dock/localization.html) 
I have a problem here. If you have the problem here too, please create new issue and notify me (I will reproduce this bug)
5 Open PO file of your language in poedit or Gtranslator (and find the "Update from POT File" option)
![obraz](https://user-images.githubusercontent.com/23406555/66491395-f2cb5180-eab2-11e9-9ac8-2c33bcaf971f.png)

6 Translate it and save changes.
7 In terminal: git status to check changes
![obraz](https://user-images.githubusercontent.com/23406555/66491591-4d64ad80-eab3-11e9-9864-2ed115e35076.png)

8 Add new file (git add filepath/file)
![obraz](https://user-images.githubusercontent.com/23406555/66492620-011a6d00-eab5-11e9-8dda-c6acc9fbf76e.png)

9 git commit, describe your changes, CTRL + S to save and then CTRL + X to exit
![obraz](https://user-images.githubusercontent.com/23406555/66492350-8e10f680-eab4-11e9-9be6-2e27062b509c.png)

10 Now call command "git push" to push your changes to your repo but because you create new branch, first time you must use "git push --set-upstream origin <branch>" See screenshot.
![obraz](https://user-images.githubusercontent.com/23406555/66492216-52762c80-eab4-11e9-81f1-00aa8f97af0e.png)

11 Go to your profile on GitHub and make pull request:
![obraz](https://user-images.githubusercontent.com/23406555/66492841-56567e80-eab5-11e9-8e6c-971b895ddf73.png)
and
![obraz](https://user-images.githubusercontent.com/23406555/66492898-7128f300-eab5-11e9-9244-7c6f5fb68558.png)

**Comment by laichiaheng** [comment]
@pyroxar Done. https://github.com/micheleg/dash-to-dock/pull/1013
But I still don't see the "Trash", "Empty Trash", "Mount", "Unmount" in the po file.

**Comment by pyroxar** [comment]
@laichiaheng did you can use "make potfile" command? If you can't, please make new issue about this.

**Comment by pyroxar** [comment]
You must have 'intltool'.
'apt install intltool' works for me.
Make completely new pot file (delete old and make the command ' make potfile).
Now you should have new translations (after update your po file from pot file, see above)
![image](https://user-images.githubusercontent.com/23406555/66550845-89951e00-eb46-11e9-88e6-dcb43ef68399.png)

**Comment by pyroxar** [comment]
When you do it, make new pull request and i will review your changes and you will review my changes, ok? :)
https://github.com/micheleg/dash-to-dock/pull/1014

![image](https://user-images.githubusercontent.com/23406555/66552591-e6de9e80-eb49-11e9-92b4-39e3f4cab4da.png)
![image](https://user-images.githubusercontent.com/23406555/66552623-f958d800-eb49-11e9-8dd0-8cd99447885d.png)

**Comment by laichiaheng** [comment]
@pyroxar It does this: 
```
mkdir -p po
xgettext -k --keyword=__ --keyword=N__ --add-comments='Translators:' -o po/dashtodock.pot --package-name "Dash to Dock" prefs.js appIcons.js locations.js
intltool-extract --type=gettext/glade Settings.ui
Generating C format header file for translation.
Wrote Settings.ui.h
xgettext -k --keyword=_ --keyword=N_ --join-existing -o po/dashtodock.pot Settings.ui.h
```
I have removed the po directory and run `make potfile`, I still don't see the Trash in the options.

**Comment by pyroxar** [comment]
Delete only pot file, not po directory.

**Comment by laichiaheng** [comment]
> Delete only pot file, not po directory.
> 
> Open your po file in poedit and update (from pot file, "Catalogue > Update...")

Yes, I have done that, but still no "Trash" and "Empty Trash" in the options.
![2019-10-10 18-31-54 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/66561541-42318080-eb8c-11e9-8cf1-540c0fe1a9a6.png)
![2019-10-10 18-30-09 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/66561561-478ecb00-eb8c-11e9-8346-b85b16174fd9.png)

**Comment by pyroxar** [comment]
I don't know this second command, use your program to update po file form pot file.

**Comment by laichiaheng** [comment]
> I don't know this second command, use your program to update po file form pot file.

![2019-10-10 18-34-09 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/66561728-93da0b00-eb8c-11e9-800b-251daabf2cca.png)
![2019-10-10 18-30-09 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/66561561-478ecb00-eb8c-11e9-8346-b85b16174fd9.png)

**Comment by pyroxar** [comment]
Which version you have?
![image](https://user-images.githubusercontent.com/23406555/66562137-43968500-eb5b-11e9-9466-e25c8c55614b.png)

I update the file, use it:
https://send.firefox.com/download/e844ab5a33d3cff2/#49cKq2pVjVoMAYo4B4_zZA

**Comment by pyroxar** [comment]
![image](https://user-images.githubusercontent.com/23406555/66562376-d3d4ca00-eb5b-11e9-905f-b3d1244de74a.png)

**Comment by laichiaheng** [comment]
@pyroxar 
It's from the Manjaro repository.
![2019-10-10 19-33-23 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/66565400-efa89200-eb94-11e9-941e-0343f42d632e.png)
Thanks for the file!! Love you!

**Comment by laichiaheng** [comment]
> Which version you have?
> ![image](https://user-images.githubusercontent.com/23406555/66562137-43968500-eb5b-11e9-9466-e25c8c55614b.png)
> 
> I update the file, use it:
> https://send.firefox.com/download/e844ab5a33d3cff2/#49cKq2pVjVoMAYo4B4_zZA

Could you share it again? I have lost the file.

**Comment by pyroxar** [comment]
OK
[zh_TW.po.zip](https://github.com/micheleg/dash-to-dock/files/3712889/zh_TW.po.zip)

**Comment by laichiaheng** [comment]
> OK
> [zh_TW.po.zip](https://github.com/micheleg/dash-to-dock/files/3712889/zh_TW.po.zip)

Thanks!
I have a question, what situation will the "Eject" be used?

**Comment by laichiaheng** [comment]
@pyroxar Done
https://github.com/micheleg/dash-to-dock/pull/1016

**Comment by pyroxar** [comment]
I suspect that eject is when you disconnect your device, unmount when you unmount volume.
https://en.wikipedia.org/wiki/Volume_(computing)
