### ISSUE TITLE
[Trash] No empty trash option and without change icon [Arch]

### ISSUE THREAD

**Issue by swatquest** [micheleg/dash-to-dock#1018]
You don't change the icon here and you don't have the option to empty the trash
To work needs some dependency?

$ls  .local/share/Trash/files 
'Captura de tela de 2019-10-10 17-25-48.png'  'Documento sem título 2'
'Documento sem título 1'                      'Empty [File']

[dash-to-panel.jpg](https://postimg.cc/w1gLdr54)

**Comment by storm119** [comment]
Hi,

Not sure if this "issue" (trash icon not updated + no right-click to trash icon for "empty trash" function) due to some limitation to Arch distro (would love to hear confirmation from the author @micheleg or from the other contributors).

Anyway...i used (thanks to) [kerry_s's scripts](https://ubuntuforums.org/showthread.php?t=2391367) to achieve this functionality...just head-up to the link and at the last page download the latest "trash.zip"...
```
Instructions/HowTo...
1- extract it (trash.zip) to $Home folder
2- within the ~/trash folder right-click open terminal
3- type ./trash.sh -s
4- logout and login again
5- search the trash and add it to favourite
6- done! 
```
`(i) Make sure to disable "show trash can" in DtD settings`
`(ii) Bewarned the sound (deleting+emptying)...but you can "disable" it`
`(iii) Running DtD on Manjaro Arch (Gnome 3.34)` 

You welcome!

**Comment by drakkan** [comment]
Please take a look here:

https://bugs.archlinux.org/task/62860

as workaround you can run:

```
setcap -r /usr/bin/gnome-shell
```

**Comment by swatquest** [comment]
drakkan, thanks.
It worked
