### ISSUE TITLE
Show Applications has darker background color

### ISSUE THREAD

**Issue by adrianbienias** [micheleg/dash-to-dock#1063]
How to remove the additional darker background color from "Show Applications"?
![Screenshot from 2019-11-24 18-53-42](https://user-images.githubusercontent.com/25237195/69498894-1294c880-0eed-11ea-9e30-eca772481bb2.png)

**Comment by enesdemirag** [comment]
![Screenshot from 2020-03-14 23-28-29](https://user-images.githubusercontent.com/26373568/76689884-936a0280-664b-11ea-9223-4c8b2c9a7d29.png)

I feel you bro.. :disappointed:

**Comment by enesdemirag** [comment]
Hi. I fixed this issue. The reason for this is I was using **gnome user themes extension** and because I use **arc-dark theme***, Show Applications icon became darker.

To fix this edit  ```gnome-shell.css``` file under ```/usr/share/themes/Arc-Dark/gnome-shell/``` and comment or delete the section below.
```
.show-apps .overview-icon {
  background-color: rgba(0, 0, 0, 0.5);
  border-radius: 2px;
  border: 0px solid; }
```

After that restart your PC or just press **Alt+F2** and type **r**. This will restart the gnome shell.
