### ISSUE TITLE
Error in the js script

### ISSUE THREAD

**Issue by cix71** [micheleg/dash-to-dock#1188]
When there are no icons in the dock (e.g. trash icon), the dock doesn't work well. In this case, the icons don't appear when you open an application, they don't disappear when you close an application

On log:
JS ERROR: TypeError: firstIcon is undefined
_adjustIconSize@/home/cix/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:612:9
_redisplay@/home/cix/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:841:14
_runDeferredWork@resource:///org/gnome/shell/ui/main.js:687:31
_runBeforeRedrawQueue@resource:///org/gnome/shell/ui/main.js:702:9
_queueBeforeRedraw/<@resource:///org/gnome/shell/ui/main.js:711:13

**Comment by schiorean** [comment]
System: Pop!_OS 20.04 LTS
Gnome Shell: 3.36.1
Dash To Dock: master (I tried with the version via extensions.gnome.org, same problems)

Confirming, the error message in my logs is:

JS ERROR: TypeError: firstIcon is undefined
_adjustIconSize@/home/sorin/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:612:9
_redisplay@/home/sorin/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:841:14
_runDeferredWork@resource:///org/gnome/shell/ui/main.js:691:31
_runAllDeferredWork@resource:///org/gnome/shell/ui/main.js:700:9
queueDeferredWork/_deferredTimeoutId<@resource:///org/gnome/shell/ui/main.js:781:13`

**Comment by UA27** [comment]
Same on Ubuntu 20.04 with ubuntu-desktop's Gnome Shell version 3.36.1 and all dconf entries at default (except for "show-favorites", "show-mounts", "show-show-apps-button" and "show-trash" obviously).

Both the extensions.gnome.org's Dash to Dock release version 68 and the default ubuntu-dock extension throws the error twice at startup. Once from the redraw queue and a second time from "updateCustomTheme":

```
JS ERROR: TypeError: firstIcon is undefined
_adjustIconSize@~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:612:9
_redisplay@~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:841:14
updateCustomTheme@~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/theming.js:214:20
_initialize@~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:399:28

JS ERROR: TypeError: firstIcon is undefined
_adjustIconSize@~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:612:9
_redisplay@~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/dash.js:841:14
_runDeferredWork@resource:///org/gnome/shell/ui/main.js:687:31
_runBeforeRedrawQueue@resource:///org/gnome/shell/ui/main.js:702:9
_queueBeforeRedraw/<@resource:///org/gnome/shell/ui/main.js:711:13
```

Also want to point out that the "Show Applications" button does not have a valid icon on initialization using my setup, so the errors above are also thrown when it is the only (or first) icon on the dock.

Debugging the _adjustIconSize's values (with favourites and trash disabled; meaning show-apps is the only visible icon on initialization) I get:

```
firstIcon: undefined
firstButton.icon: undefined
firstButton: [0x556f94714150 StButton.show-apps:first-child last-child]
iconChildren[0].child: [0x556f94714150 StButton.show-apps:first-child last-child]
iconChildren[0]: [0x556f94710b80 Gjs_dash-to-dock_micxgx_gmail_com_appIcons_DashToDock_MyShowAppsIcon.dash-item-container:last-child]
```

or (when "show-show-apps" is disabled):

```
firstIcon: undefined
firstButton.icon: undefined
firstButton: [0x564d39229900 StButton.show-apps]
iconChildren[0].child: [0x564d39229900 StButton.show-apps]
iconChildren[0]: [0x564d39226b90 Gjs_dash-to-dock_micxgx_gmail_com_appIcons_DashToDock_MyShowAppsIcon.dash-item-container:last-child]
```

Oh and enabling "show-apps-at-top" doesn't throw the errors unless "show-apps" is the only icon/button on the dock since it's a returned element of "this._box.get_children()".

I'll be using schiorean's #1222 fix for now.

**Comment by awenger** [comment]
It looks like there was a regression on this bug with ubuntu 21.10: https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1880570

I think it was introduced here: https://github.com/micheleg/dash-to-dock/commit/af1328f528044595898a40f90c7fc8ae29a3c6c3#diff-13c52f01fd531f7fb3f8580b6636024d1a1ba003ae2dedddbe5a8b0095703d4bR596-R599

Because the destructuring assignment happens before the null/undefined/falsy check
