### ISSUE TITLE
Support for gnome 3.38

### ISSUE THREAD

**Issue by Voodlaz** [micheleg/dash-to-dock#1313]
When extension will support new gnome 3.38?

**Comment by edier88** [comment]
Gnome 3.38 ??
They haven't even supported Gnome 3.36, I've been waiting for the whole year 2020 and nothing happens, they don't update a single line of code and in my Fedora 32 it runs like a crap.
I'm willing to make a fork for Fedora exclusively, or at least for all those distributions that apply Gnome without any variance, cause I can see, this extension is too friendly with Ubuntu and its derivatives but it's not so good with distributions that have Gnome implemented without any customization, which I think, is better. (Fedora, Archlinux, etc)

**Comment by Voodlaz** [comment]
@edier88 uhh but they are supporting gnome 3.36

https://extensions.gnome.org/extension/307/dash-to-dock/

**Comment by Voodlaz** [comment]
@edier88 Also you can use vanilla gnome on Ubuntu, just google it.

**Comment by edier88** [comment]
> @edier88 uhh but they are supporting gnome 3.36
> 
> https://extensions.gnome.org/extension/307/dash-to-dock/

No, they're not fully supporting it for now:
https://micheleg.github.io/dash-to-dock/
There's nothing with the name of "3.38" in that page, they only did a fix, but it's not a complete support.
And I can use Vanilla Gnome on Ubuntu as you say, but why I should do that? I don't work with Ubuntu I work with Fedora, it's my job. 
Thank you for your replies!

**Comment by lepa22** [comment]
@Voodlaz Support for GNOME 3.38 seems to have been added with the latest pull request (#1309).

@edier88 3.36 is fully supported, it's just the webpage that isn't updated to reflect it. Admittedly though, the development of the extension is slower than it used to be.

**Comment by edier88** [comment]
@lepa22 I wrote an issue months ago, in Arch Linux and Fedora with Gnome 3.36 Dash to Dock behaves unexpectedly. The "intelligent autohide" does not work at all. It makes the dock hide whenever it wants. 
They've put a fix on Gnome 3.36 and focused entirely in Ubuntu and derivatives, but Dash to Dock misbehaves in all other distros who implement Gnome out of the box without any customization, which is the best way to do it to avoid security problems, unlike Ubuntu, that has a bunch of security problems due to its crazy customizations.

Anyway, thank you for your reply

**Comment by Voodlaz** [comment]
> @Voodlaz Support for GNOME 3.38 seems to have been added with the latest pull request (#1309).
> 
> @edier88 3.36 is fully supported, it's just the webpage that isn't updated to reflect it. Admittedly though, the development of the extension is slower than it used to be.

cool, I can close issue
