### ISSUE TITLE
v39 broke autohide

### ISSUE THREAD

**Issue by ace214** [micheleg/dash-to-dock#146]
The latest version broke autohide for me, regardless of the pressure setting.

If I downgrade to v38, it works again. I'm on Arch with GNOME 3.14.2.

**Comment by micheleg** [comment]
What does it mean? the dock never appears or it's not triggered by mouse hover?

**Comment by ace214** [comment]
Thanks for your quick response. The dock is not triggered by mouse hover. Intellihide is working.

**Comment by micheleg** [comment]
Mmmm, I'm on 3.14.2 too and I don't have such problem. Please try without other extensions or custom theme. Can you post your settings via the command:
<code>dconf dump /org/gnome/shell/extensions/dash-to-dock/</code>

**Comment by ace214** [comment]
Disabling extensions and themes didn't help. It appears that it was some problem with the packaging from the repo (antergos). I installed it from the GNOME website and it was fine.

Thanks for your attention.

Settings:
show-apps-at-top=false
dock-fixed=false
intellihide=true
pressure-threshold=10.0
autohide=true
custom-theme-running-dots=false
custom-theme-shrink=false
show-running=true
intellihide-perapp=true

**Comment by ace214** [comment]
Filed bug at Antergos: https://github.com/Antergos/antergos-packages/issues/33

**Comment by ainola** [comment]
I just upgraded and am experiencing autohide issues. Not sure what OP's specific issues were but mine happen when launching an application with the dock. The dock will not autohide after launching the application. It has a slight chance of hiding again when clicking with the mouse rather than hitting [ENTER] with the keyboard.

Here is a small video demonstrating the behavior:
http://ainola.sdf.org/bug.webm

dconf returns:

>extend-height=false
intellihide=false
scroll-switch-workspace-dead-time=100
show-delay=0.10000000000000001
animation-time=0.10000000000000001
pressure-threshold=160.0
autohide=true
apply-custom-theme=false
scroll-switch-workspace-whole=false
custom-theme-running-dots=false
custom-theme-shrink=true
background-opacity=0.67000000000000004
opaque-background=true
require-pressure-to-show=true
scroll-switch-workspace-one-at-a-time=true

**Comment by micheleg** [comment]
I see you are on arch as well. Where did you install the extension from? Can you confirm that you are using the extension from the extension website and if the problem appear only after the last update?

**Comment by ainola** [comment]
Yes, I am on the latest arch and only ever use the gnome extensions website.

**Comment by ainola** [comment]
Sorry, I forgot to say that I'm not sure if I was running a few versions behind or not as I sparingly look for updates for gnome-shell extensions. But whatever version I was running before this one did not have the issue.

**Comment by micheleg** [comment]
So is the problem gone with the latest version? I'm not sure I understood.

**Comment by ainola** [comment]
Sorry, I meant that I'm not sure if I was on v38 or v37 before upgrading. The issue is with the latest v39.

**Comment by micheleg** [comment]
I found the bug. In the meantime, disabling the pressure option should workaround the issue. I will upload a fix soon.

**Comment by micheleg** [comment]
88ed57257cab9e48e50770a9ea0701783a73f089 should have fixed the issue.

**Comment by ainola** [comment]
Yep, that fixes it! You're the man, micheleg <3
