### ISSUE TITLE
Dash to Dock is behaving badly with Blur my Shell

### ISSUE THREAD

**Issue by nafunii** [micheleg/dash-to-dock#1533]
I've been tinkering with the css and seem to be lost. 
For Reference, here's what I've been trying to remove:
![image](https://user-images.githubusercontent.com/53419401/137049693-38a552c6-3c44-4c1d-b38d-a8711531cd3c.png)
![image](https://user-images.githubusercontent.com/53419401/137049730-43a2a34b-216e-4293-bab5-c863bff6b032.png)

**Comment by Bananaman** [comment]
This is a Blur My Shell problem, not related to Dash to Dock.

Without even looking at any of the code of any extensions, Blur My Shell is totally obviously generating a blurred texture and then applying it as a permanent background to GNOME's "Dash".

Meanwhile, Dash to Dock simply takes the real GNOME Dash and moves it elsewhere on screen.

Therein is the problem. Blur My Shell needs to detect Dash to Dock and NOT add a blurred background to it.

**Comment by Bananaman** [comment]
@nafunii I found a workaround. Turn off "Blur: dash" in the Blur My Shell settings:

https://github.com/micheleg/dash-to-dock/issues/1587#issuecomment-974862400

But still, it should be reported to Blur My Shell so that they automatically disable the dock blurry when Dash to Dock is installed. Blur My Shell is responsible for it since they're the ones adding the blur stuff to the dock. :)

**Comment by Bananaman** [comment]
Just a small update to let everyone know: Blur My Shell has added detection of dash2dock and tries to do the right thing when both extensions are enabled. For me, it still never works and still looks corrupt. So I still go into the Blur My Shell settings and turn off Dash blur. :)

**Comment by sachin-acharya-projects** [comment]
You can use custom Properties and increase brightness to max. It does not remove the weird background but makes it hard to see. It worked for me.
