### ISSUE TITLE
Add option to toggle Dash to Dock animation on windows urgency

### ISSUE THREAD

**Issue by aindriu80** [micheleg/dash-to-dock#1557]
Hi,

I am running Dash To Dock on Pop OS! 21.10 beta (Gnome 40.5) on a dual monitor desktop machine and I have Dash To Dock to hide unless I place the mouse over it.  

Everything is working great but the Dash To Dock panel pops up whenever an app completes a task.  For example, using Grsync to copy files, once the app has copied files over the Dash To Dock panel becomes visible (a bit of a wave) and then it disappears again.

How do I stop Dash To Dock from popping up like this?

**Comment by 3v1n0** [comment]
That's a feature, the same happened for the old Unity dock as well.

However, we may provide an option to disable this if that's bothering.

**Comment by P1zz4br0etch3n** [comment]
While I really appreciate such features it is very annoying if you have to use applications like MS Teams. It even pops up when I receive a new message in an active chat and while I may be answering a previous message. Like that I cannot read what I'm writing because the dash covers the input box. I know that is a MS Teams issue, but I bet they won't fix it in 10 years. So please add an option to turn this off or provide a quick workaround. Thanks!

**Comment by 3v1n0** [comment]
Closed via c0f806c0e9f6314332127fd24bddf0a36b90d803
