### ISSUE TITLE
Gray box underneath parts of dock on Gnome 41

### ISSUE THREAD

**Issue by theomega24** [micheleg/dash-to-dock#1587]
Hello, I have recently installed gnome 41 on Arch, EndeavourOS, and now Fedora, and dash to dock has had the same project on all of them.

There is a small gray box underneath the dock (chrome icon):
![image](https://user-images.githubusercontent.com/69646789/140656652-bd967b98-f82d-4cfa-88f1-7ddf6c103775.png)

**Comment by sidharthpunathil** [comment]
I am having the same problem. 
![image](https://user-images.githubusercontent.com/31244727/140903197-e2c757e2-8dd7-4fbd-b252-1b4976f8940b.png)

**Comment by vvzxcvv** [comment]
same, fedora 35
![image](https://user-images.githubusercontent.com/67964978/142724026-76f30aa3-5e59-45ef-85a6-53390ef0318f.png)

**Comment by vvzxcvv** [comment]
disable your blur extensions, fixed for me

**Comment by jeremy-lilly** [comment]
I had this same problem -- Its due to some conflict with extensions that apply a blur effects to desktop (like Blur my Shell). You need to adjust the settings so that the dash isn't blurred.

**Comment by sidharthpunathil** [comment]
> disable your blur extensions, fixed for me

![image](https://user-images.githubusercontent.com/31244727/142773061-8a2e33f1-caa5-4d1e-ba5c-199a6f5609cf.png)
Thanks! that fixed my issue!

**Comment by Bananaman** [comment]
@sidharthpunathil Huge thanks! I had disabled Blur My Shell completely, but your answer is much better. Just disable "Blur: dash" and that's enough to fix it! :) There's no need to disable "app folders" like your screenshot. I think app folders look much better enabled (blurred background in app launcher folders instead of a gray, opaque one).
