### ISSUE TITLE
ubuntu-dock branch - Gnome 42 intellihide issues

### ISSUE THREAD

**Issue by Pshemas** [micheleg/dash-to-dock#1690]
First of all - thank you for those committing to this branch. It's basically what for me keeps this (IMO essential) extension alive.

Glad to see updates for Gnome 42. I've encountered one annoying issue - intellihide often "locks" and does not hide the dock. It's like keeping highlight on one of the items in the dock and where it is in this state the dock stays on top. 
By trying to hove over the dock several times and moving out or (/ and) by bringing the dash up I can sometimes make it hide again.

If you won't get what's the issue is about and would like to know more let me know - I'll try to record a video, it should explain it better.
I'm on OpenSUSE Tumbleweed, Gnome 42.

**Comment by julianfairfax** [comment]
I also have this problem. When using Dash to Dock on GNOME 42 via https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock-gnome42-git with autohide enabled and push to show off, moving the cursor directly from the dock to an app window and clicking on it doesn't make it go away. To make it go away I have to move my cursor out of the dock where no window is behind it. This shouldn't be normal behaviour as far as I know. This only happens on GNOME 42, so it must be an issue with the extension and GNOME 42.

**Comment by JisJ3rry** [comment]
This is not a Dash to Dock problem, it's a Mutter 42 problem. If you move the cursor away from any overlay (top bar, dash) into a window without passing by the desktop, the item you hovered in the overlay remains selected. When this happens, Dash to Dock thinks you're still on the dock so it doesn't make it disappear.
It's fixed in commit [0280b0aa](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2321/diffs?commit_id=0280b0aaa563db65bf79a3643f6a9e8e76bfe458) on GNOME's GitLab.
So, either rebuild Mutter from sources or wait for GNOME 42.1.

**Comment by 3v1n0** [comment]
Indeed we have that commit in ubuntu and we didn't notice it so far...
