### ISSUE TITLE
Feature Request: Centered Icons in Panel Mode

### ISSUE THREAD

**Issue by maxlahn** [micheleg/dash-to-dock#1746]
Basically the title. I use the "panel mode" (which extends the dock), but all my favorite apps are on the left-hand side. It'd be cool we could choose for them to be centered.

**Comment by Anderson0xFF** [comment]
I liked, I'm looking for something about it.

**Comment by janpansa** [comment]
Please add this feature, should be easy enough?

**Comment by Alt37** [comment]
Centered panel would definitely improve both presentation and usability.
1. Centered items on the panel look much closer to original dash design than current "favorite/running apps on the left, apps icon on the right"
2. I can use "Dock" instead of "Panel" to achieve similar effect. But panel look so much better and far less distracting with some bright wallpaper
3. Most other popular desktop OS (macOS, ChromeOS, Windows) center apps on the panel.

![dash_to_dock__bottom_panel](https://user-images.githubusercontent.com/44649402/195506539-7c46cb51-0c65-44e2-97d6-eb36ab811d86.jpg)
![dash_to_dock_dock](https://user-images.githubusercontent.com/44649402/195506584-fc9b657d-4dee-4910-984f-ce096aeb4a68.jpg)
![dash_to_dock__bottom_panel_centered](https://user-images.githubusercontent.com/44649402/195506604-1e24c911-ba33-4655-876d-53ab9f23810e.jpg)
![original_dash](https://user-images.githubusercontent.com/44649402/195506619-c7286b76-930a-4ca3-b991-2d9e6356005f.jpg)

I've made a simple "proof of concept" patch which works well but not ready for merge because:
- With this patch some options ("Move the application button at the beggining of the dock", "Panel mode") don't update panel properly in a real time (you also need to change "Positiion on the screen" or reload extension/Shell)
- it doesn't add option, just partly replaces current design

@3v1n0 , @micheleg 
What is your opinion about adding such option and maybe even making it default for horizontal panel?
Thanks!

**Comment by 3v1n0** [comment]
I'm ok adding an option, not to making or default though

**Comment by roracle** [comment]
> I'm ok adding an option, not to making or default though

How long before we can expect the change? I would like this as well. :)

**Comment by SassyJammy** [comment]
Yes, I would love such a feature. The only extensions that achieve this are Dash to Panel and Dash to Dock for COSMIC.

However, they both come with their downsides in my opinion:

Dash to Panel:
- Looks really square and gets rid of the GNOME feel

Dash to Dock for COSMIC:
- The default GNOME workspace switcher gets messed up

There isn't a dock extension that really does the centered icons in a good way...
Hope this gets added here soon.

**Comment by 3v1n0** [comment]
This is implemented in https://github.com/micheleg/dash-to-dock/pull/1998 please test it :)

**Comment by KakeyaK** [comment]
> This is implemented in #1998 please test it :)

Couldn't find the options to center the icons, even after installing the latest version through cloning master branch. Am I doing something wrong?

**Comment by 3v1n0** [comment]
@KakeyaK the PR is not merged yet, you should install it from that branch: https://github.com/3v1n0/dash-to-dock/tree/always-centered-panel-mode

**Comment by Racsuu** [comment]
hi, is working perfectly here, also thanks for add the option to move the show apps icon to the edge or to the center on panel mode! (using it on the center here)
![imagen](https://user-images.githubusercontent.com/129788380/234723805-7ee10319-08a3-47f7-a92e-57cfe2d51464.png)

**Comment by ionutbortis** [comment]
I think the fix for this is causing the issues from #2010

**Comment by tegar-bbizengine** [comment]
> hi, is working perfectly here, also thanks for add the option to move the show apps icon to the edge or to the center on panel mode! (using it on the center here)

how to do it?

**Comment by xalt7x** [comment]
> > hi, is working perfectly here, also thanks for add the option to move the show apps icon to the edge or to the center on panel mode! (using it on the center here)
> 
> how to do it?

Dash to Dock Settings:
- Position and size > [v] Place icons to the center
- Launchers > [ ] Put Show Application in a dock edge when using Panel mode

```
dconf write /org/gnome/shell/extensions/dash-to-dock/always-center-icons 'true'
dconf write /org/gnome/shell/extensions/dash-to-dock/show-apps-always-in-the-edge 'false'
```
