### ISSUE TITLE
Feature request: Cycle trough windows

### ISSUE THREAD

**Issue by vincent-t** [micheleg/dash-to-dock#183]
Could you please add an option to cycle through open windows of an application via mouse wheel.
best regards

**Comment by micheleg** [comment]
The scroll is used to scroll the dock itself at the moment, so I need to think of a way to make things coexist.

**Comment by gabrielmoreira** [comment]
I have used Plank, Docky, Cairo-Dock and Dash-to-Dock.

But only Dash-to-Dock doesn't cycle open windows using mouse wheel.

**Comment by micheleg** [comment]
@gabrielmoreira that's doesn't mean we can't do something different :) That said, the problem is the coexistence with the other scroll behaviour, namely workspace switching and more importantly dock scrolling with fixed icon option. I gess both Plank and Cairo-Dock always shrink in size to allocate more icons instead?

**Comment by Deus-Rex** [comment]
Is it possible to be able to change the dock scrolling to either a click or hover to drag? I'm sure that's how Unity has it, which lets that be able to implement scroll to cycle through windows.

I'd very much appreciate being able to cycle by scrolling as well. It's the only thing this dock is missing.

**Comment by micheleg** [comment]
Cycle by scrolling was implemented by #428.
