### ISSUE TITLE
Center icons in Panel Mode

### ISSUE THREAD

**Issue by N0BOX** [micheleg/dash-to-dock#187]
The last thing I need to make Gnome3 feel the way I normally configure Xfce4 would be to put the dock into "Panel Mode", but I always center the icons, which isn't possible with this extension (at least, I can't figure out how to do it).  Could an option be added to center the icons when the dock is in panel mode?

You might also consider, instead of just a "Center icons" option, adding a slider that allows you to place the icons anywhere along the panelized dock.  You could consider the point that the slider is at to be the center point of the collection of icons.  As the slider approaches the edge of the screen, the icons should stop, that way the icons can be easily placed at either end of the screen by putting the slider all the way to the left or right.  A "notch" (kind of like the lines on the "Icon size limit" slider) should be placed in the center so it's easy to find the center point of the slider.

Thanks for a great extension!

**Comment by micheleg** [comment]
Hi,

I don't think I will implement anything like what you suggest. Centering the icons is not totally trivial  due to the different containers involved, and I'm not convinced it's worth to implement such option beside the point of view of aesthetics which is a matter of preferences. As said elsewhere, any option added complicate the long term maintainability, so I'm carefull in considering new features, given the limited time I can dedicate to this extension. Nevertheless, I changed my mind in the past so I might reconsider your idea.
