### ISSUE TITLE
Removable Disk popup covered by dock

### ISSUE THREAD

**Issue by lnx64** [micheleg/dash-to-dock#195]
When inserting a removable disc, like a CD, thumb drive, or anything, dash to dock seems to cover up the popup that asks what I want to do with the disk, as seen here.

http://i.imgur.com/nroKwg8.png

Not sure what's causing it but hopefully it can be fixed in a newer version.

I'm running version 45 as that's the one offered on Gnome's website as an extension.

**Comment by micheleg** [comment]
This has been known since the introduction of the bottom option (http://micheleg.github.io/dash-to-dock/release/2015/01/05/new-release-v36.html), and since then I planned not to solve this problem at the extension level as notifications have been moved to the top of the screen in GNOME 3.16. As you are still on GNOME 3.14, as I am, I suggest you to use this extension https://extensions.gnome.org/extension/708/panel-osd/.
