### ISSUE TITLE
[Feature Request] Create option for ALL Windows upon a right click. 

### ISSUE THREAD

**Issue by postnick** [micheleg/dash-to-dock#1996]
Please see refrence to this enhancement in the dash-to-dock cosmic and add the options to the main line.

[All Windows Jammy #1 42](https://github.com/pop-os/cosmic-dock/pull/142)

This will improve functionality when right clicking and remove a click for when you want to switch windows.

**Comment by 3v1n0** [comment]
This is already supported since commit 3cbe4b3ecca1d14f23d9c1b32555eeb1437e3aa6 there's not a setting, but it can be configured from dconf (or use `GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas gsettings set org.gnome.shell.extensions.dash-to-dock default-windows-preview-to-open true`, or `GSETTINGS_SCHEMA_DIR=$HOME/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas gsettings list org.gnome.shell.extensions.dash-to-dock` to see them all).

**Comment by postnick** [comment]
Hey Cool! Thank you, Sorry for the duplicate - This I think would still be a very valubale quick toggle in the setting app. 

I have this written down in a note - but I was missing the extra bit. 
`gsettings set org.gnome.shell.extensions.dash-to-dock default-windows-preview-to-open true`
