### ISSUE TITLE
Maximized applications resizes to screenwide after system waking up from sleep when dock auto hide disabled.

### ISSUE THREAD

**Issue by MusaSSH** [micheleg/dash-to-dock#2089]
With Dash to Dock's auto-hide feature disabled, maximizing an application resizes them until the top limit of the dock, which is the normal behavior.

While the application is maximized, try suspending the system (in my case that's closing the lid) and then wake it up, login to the system again and you'll see that application is now maximized to the whole area, dock is still standing on top of the application. To fix this I need to remaximize all my open and maximized applications.

**Comment by vanvugt** [comment]
This issue is already being tracked in:
 * https://gitlab.gnome.org/GNOME/mutter/-/issues/230
 * https://gitlab.gnome.org/GNOME/mutter/-/issues/2445

and probably others.

Although your Dash to Dock settings may be a factor in triggering the bug I don't think we should track it here. Maintaining the correct window size is Mutter's responsibility.
