### ISSUE TITLE
compatibilty with topicons extension

### ISSUE THREAD

**Issue by cedricbrx** [micheleg/dash-to-dock#209]
Hi,

I'm using your extensions with appindicator support or topicons. Since the last update to version 48 of dash to dock. The icons from appindicator/topicons disappears in the upper left corner.
The extensions were working well together under version 45.

Best Regards,

George

**Comment by micheleg** [comment]
Hi George,

Thanks for your bug report. This is a strange behaviour. Can you confirm that the bug is due to the update of dash-to-dock rather than to an update of the appindicator/topicons extensions? I should not be messing with anything related at all, but I might be forgetting something right now.

Michele

**Comment by cedricbrx** [comment]
Appindicator or topicons didn't got an updated since months. I have an laptop where i didn't update the extension from v45 to v48 and there i don't have the problem of disappearing icons.

Geroge

**Comment by micheleg** [comment]
I'm using v48 in 3.14 with the topicons extension and I cant reproduce the bug. Is there a way to deterministically reproduce it. When are the top icons disappearing?

**Comment by micheleg** [comment]
Are you still experiencing this issue?
