### ISSUE TITLE
Feature request: Option to not reshuffle applications.

### ISSUE THREAD

**Issue by OlegOAndreev** [micheleg/dash-to-dock#21]
A useful addition to the extension would be an option to fix the locations of application icons in the dock and not shuffle them based on LRU order.

**Comment by karate** [comment]
When "Show running applications" is checked, running applications that are not in favorites are shown at the end of the dock. Those are sorted by last used application, so their position changes when you click through them. What I think @OlegOAndreev meant, is to have an option to keep the order of the applications fixed. I'd also find that useful.

**Comment by micheleg** [comment]
I think commit [805fd6c4d72d55afa3f25bd51a373e990c7f0b96] should have fixed this issue.

**Comment by karate** [comment]
You're right. I was using the [extensions.gnome.org](https://extensions.gnome.org/extension/307/dash-to-dock/) version. I just installed the latest version from github and it works.

**Comment by andresmeidla** [comment]
using latest commit e564630423981777902f308dc093dd512f9be90c on ubuntu 17.10
and noticing that my running application are in the order of when they are last used.
i see the code [805fd6c] for keeping the order static but it does not seem to be applied for me.
Is there something im missing here?

**Comment by micheleg** [comment]
@andresmeidla : do you mean that the order changes during the session, i.e. that whenever you change the focus application this get positioned as the topmost running launcher (after the fvorites)?

**Comment by andresmeidla** [comment]
Yes, and i mean the applications that are stacked together.

**Comment by micheleg** [comment]
What do you mean by "stacked together"? Are we talking about the order of the launchers or the ordering of each application windows?

**Comment by andresmeidla** [comment]
I mean each application window.
Created some screenshots:
I have three gedit application windows: First, Second and Third.
What I would like is to have these application windows to always be ordered the way they were launched, like so: First, Second, Third
![1](https://user-images.githubusercontent.com/8395526/32718841-0f570efe-c867-11e7-9c16-33702f6d62f6.png)

But after selecting for ex the third window, they are reorded to whichever window was selected the last:
![2](https://user-images.githubusercontent.com/8395526/32718894-4a21f2ce-c867-11e7-9e7a-8e0e924437b3.png)

My goal is to have the window order be always: First, Second, Third, so I could switch between them in a consistent manner, otherwise I'd have to read the application names every time im switching between the windows.
Can that be achieved somehow?

**Comment by andresmeidla** [comment]
same thing requested here: #639
