### ISSUE TITLE
"Show Details" menu item is untranslatable

### ISSUE THREAD

**Issue by proninyaroslav** [micheleg/dash-to-dock#2104]
In the Dash To Dock menu the "Show Details" item in English, and for example this string isn't in the Russian translation and `xgettext` also doesn't see it (I run `make potfile` command):

![2023-10-11 18-35-47](https://github.com/micheleg/dash-to-dock/assets/7840559/518e356e-da8d-44c8-868c-b2d886bcddc1)

But in the original GNOME Dock the "Show Details" item is translated:

![2023-10-11 18-41-07](https://github.com/micheleg/dash-to-dock/assets/7840559/870cb044-8e65-489b-811d-df8bf788a340)

**Comment by xalt7x** [comment]
I can confirm this issue.  
Unfortunately even when this string is translated, original English message is still shown for some reason

> this string isn't in the Russian translation and `xgettext` also doesn't see it (I run `make potfile` command):

That's unrelated information
1. This string was missing in most translation files until #2093 
2. `make potfile` generates po/dashtodock.pot (template for translators). With a current "master" branch you will find the this string there,

**Comment by krystal-cao** [comment]
@proninyaroslav @xalt7x 
Because "Show Details" uses the default translation of the Gnome Shell.But the text of the Gnome Shell menu item is "App Details"
![WX20231101-102009@2x](https://github.com/micheleg/dash-to-dock/assets/13929955/b8fcf22a-1487-4cf2-810c-e2e4998b6bae)
![WX20231101-102528@2x](https://github.com/micheleg/dash-to-dock/assets/13929955/93513699-4d6f-4542-aee6-63d0c1470d7f)

**Comment by krystal-cao** [comment]
@proninyaroslav 
So you can modify _('Show Details') to __('Show Details') in line 1151 of the appIcons.js and build it yourself, I tried it and it works!

**Comment by proninyaroslav** [comment]
@krystal-cao 
This is more likely a workaround than a solution. If it uses GNOME translation then why is it only English? In the original GNOME Dock this line is translated.

**Comment by krystal-cao** [comment]
@proninyaroslav 
I'm guessing that the text on the line of the original GNOME Dock has been changed from 'Show Details' to 'App Details' since some version. 'App Details' is translated in the original GNOME Dock. 'Show Details' is not translated in the original GNOME Dock. So 'Show Details' is only English.
You could also change _('Show Details') to _('App Details') and try building it!

**Comment by proninyaroslav** [comment]
@krystal-cao 
Yes, it works. Thank you. I created a PR https://github.com/micheleg/dash-to-dock/pull/2117

**Comment by xalt7x** [comment]
@krystal-cao , thanks for finding it!
---
@proninyaroslav ,
I'd like to have it fixed as well but IMO the better approach would be just to get rid of the custom strings which already present on the GNOME Shell ("Show Details", "Launch using Integrated Graphics Card", "Launch using Discrete Graphics Card"). It should prevent such breakages but also cover more translations. For example, "Dash to Panel" didn't have this issue.

**Comment by proninyaroslav** [comment]
@xalt7x 
A cursory examination of Dash To Panel showed that they use `AppMenu` from Shell with minimal customization (only hiding some menu items based on settings). I'm not very familiar with `gettext`, but it seems to me that it is impossible to simply reuse the translation, since you need to know the source string (in this case `App Details`): https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/appMenu.js#L86. Maybe we should just take `AppMenu` as a basis and extend the class by adding custom things, but it is unknown how this will affect the future compatibility of the extension with Shell.
