### ISSUE TITLE
unity-like behavior: overview

### ISSUE THREAD

**Issue by naldir** [micheleg/dash-to-dock#211]
click action option: unity-like behavior (overview of all instances):
-when more than 1 instance are opened, show overview of all instances of app

**Comment by micheleg** [comment]
I'm not sure I understand what you are suggesting. Is this the same of #216?

**Comment by naldir** [comment]
Yep, you can mark this as closed because it is a duplicate.
Sorry for that.

**Comment by fastrizwaan** [comment]
#216 is closed and this is also closed?

**Comment by micheleg** [comment]
#216 is not closed, and I have been looking a bit into it in the last weeks.I didn't get something working in a decent way, but It's definitely something I'm willing to explore further.

**Comment by slacka** [comment]
@micheleg 
gnome has a built in 'overview of all instances' already with the alt-tab. Could you reuse this code to implement this feature?

**Comment by micheleg** [comment]
@slacka the thing that I see as more difficult is to integrate this different view in the overview, in particular dealing with with the transition from and to the other views. I think that a good starting point would be to have a mostly independent view with a fade-in transition. It has been a while since I last investigated this feature though.
