### ISSUE TITLE
Desktop crashes by locking screen via shortcut or suspend mode

### ISSUE THREAD

**Issue by MarvvanPal** [micheleg/dash-to-dock#2214]
Hi there,

after updating on version 92 of this extension I experience an issue.

Scenario:
1) Connect second screen
2) Login
3) Press Superkey for app grid
4) press superkey + L to lock
5) text/tty cursor at the top left for a second, and then GDM says hi - ready to login / All apps got closed

Errors (selection):
"Failed to create new MetaSelectionSourceMemory: Failed to create MetaAnonymousFile"
"Error reading events from display: Broken pipe"
"org.gnome.SettingsDaemon.Color.service: Main process exited, code=exited, status=1/FAILURE"

Workaround:
- Disable dash-to-docks

System:
Thinkpad X1 Yoga 2nd Gen.
openSuse Tumbleweed
Gnome 46 + Wayland

**Comment by sergio-costas** [comment]
Confirmed, but I receive a kernel crash in the moment of pressing _Windows+L_, and everything else derives from that...

![imagen](https://github.com/micheleg/dash-to-dock/assets/105285003/cd25780e-3564-4c39-b18b-7ae1cf6178e7)

I suspect that the problem is deeper in Gnome Shell, or even in St/Clutter... So I think that, at the moment, a workaround must be used, and with more time try to find the true reason for this bug.

**Comment by sergio-costas** [comment]
I wrote a workaround https://github.com/micheleg/dash-to-dock/pull/2219
