### ISSUE TITLE
Gnome 47 

### ISSUE THREAD

**Issue by ryzendew** [micheleg/dash-to-dock#2246]
Gnome 47 works if you update metadata unsure if it will stay this way but figured i open an issue

**Comment by vanvugt** [comment]
Support for 47 was only added on the master branch recently in https://github.com/micheleg/dash-to-dock/pull/2223. I want to say it's too early to update the metadata since there are months remaining before release and it's likely to break again. But since gnome-shell 47.alpha is tagged now, I don't see why not...
