### ISSUE TITLE
Background opacity not working

### ISSUE THREAD

**Issue by algamer31** [micheleg/dash-to-dock#228]
Background opacity does not work if the dash is docked to top or bottom with panel mode is set to "extend". 
GNOME 3.14

**Comment by micheleg** [comment]
It seems to work for me on GNOME 3.14, regardless of the settings? Are you using a custom theme?

**Comment by algamer31** [comment]
yes, i think that's where the problem lies. I am using Arc Theme. I have adjusted the background property of dash in the gnome-shell.css file of the theme but it doesn't affect the dash if it is on the bottom or the top.

**Comment by micheleg** [comment]
Can you send me a link to the theme?

**Comment by algamer31** [comment]
Here is the link to the theme: 
https://github.com/horst3180/Arc-theme

**Comment by micheleg** [comment]
To me opacity is ignored ignored regardless of all the other settings to me. I noticed that the problem comes from the ```border-image: url("common-assets/dash/dash-left.svg") 3 3 3 3;``` rules, which affects  the background too. I haven't investigated if this is the expected behaviour or not. If you modified the theme source, you probably removed that line from the main ```#dash``` css rule, but you need to change it for also for the ```.bottom``` and ```.bottom.extend``` etc. classes. You can use normal simple border rules if you want a border. 

As it seems they are supporting the extension dash-to-dock, maybe it's worth filing a bug report on their side? At least to see if this is the expected behaviour.

**Comment by user501254** [comment]
@micheleg, Please re-open this
See: https://github.com/horst3180/arc-theme/issues/329#issuecomment-174332966

**Comment by micheleg** [comment]
@user501254 Sorry for the late reply. Can you help me understanding the issue? the transparency setting in this extension is mainly meant as a workaround for theme not supporting directly this extension. Have the arc-theme authors problem supporting the extension? If not, think it's fine if the option does not work with that theme as I I believe themes authors know better how to integrate the dock in their design.

**Comment by user501254** [comment]
@micheleg First off, I didn't know that this setting is supposed to be a workaround. Some text mentioning this in the settings would be nice.
Coming to the issue (if we consider it as a feature), from what I understand @horst3180's theme uses custom SVG images located [here](https://github.com/horst3180/arc-theme/tree/master/common/gnome-shell/3.18/common-assets/dash) to draw the dash whose opacity can not be customized using the settings within the extension because it makes changes to the color of the dash within [_updateBackgroundOpacity](https://github.com/micheleg/dash-to-dock/blob/master/dockedDash.js#L1456). Forgive me if I am wrong.

**Comment by micheleg** [comment]
Yes, some explanation would help. That setting was for the default GNOME Shell theme prior to 3.16, when the dock was semitransparent making it difficult to be used in autohide mode, and is of help for other third-parties themes which might still have the same problem.

You understanding of the issue is correct. I cannot change the svg they are using to render the background, it's not possible as far as I know. So not much I can do on my side beside  trying to be more clear in the settings
