### ISSUE TITLE
Release for GNOME Shell 46

### ISSUE THREAD

**Issue by e-rakavest** [micheleg/dash-to-dock#2310]
I guess lots of people waiting release GNOME Shell 46. Now we have very old version(v90) with issues. Maybe you  let us know when it plan?

**Comment by vanvugt** [comment]
It sounds like you're talking about [the version of ubuntu-dock that ships with Ubuntu](https://launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock). That won't be changed because it's a stable release.

For dash-to-dock you can already [install the latest versions in GNOME 46](https://extensions.gnome.org/extension/307/dash-to-dock/). But if you do that then be sure to disable ubuntu-dock so they don't conflict (and crash).
