### ISSUE TITLE
Dash does not show even when focused window does not overlap it

### ISSUE THREAD

**Issue by saligrama** [micheleg/dash-to-dock#243]
When other windows are maximized, and I open an app that does not overlap the dock (such as `xfce4-terminal`), the dock doesn't show. For example:

![image](https://cloud.githubusercontent.com/assets/13177755/10583894/764a2820-765d-11e5-973d-6a07f80ee623.png)

But when Nautilus is restored, it works as expected:

![image](https://cloud.githubusercontent.com/assets/13177755/10583927/9345abca-765d-11e5-88d5-9d14b00177f0.png)

I have the option "Dodge only focused application's window" selected in the extension preferences.

**Comment by micheleg** [comment]
This was a deliberate choice in the new version, as briefly describer here: http://micheleg.github.io/dash-to-dock/release/2015/09/20/new-release-v49-gnome-3.18.html. See the commit message 4eabe6db9bbded for the motivations. I think this behaviour is better; at least I found myself being annoyed by the dock covering a window I was working on. The general idea, also in the case of this other change acf12a03057beab, is that it's better to have the dock hidden, as it can alwasy be retrieved by mouse hovering, rather than shown when unwanted.

**Comment by saligrama** [comment]
I liked this behavior when it was used, although I could see how it could get annoying. Is it possible to revert to an earlier version but maintain compatibility with GNOME 3.18?

**Comment by micheleg** [comment]
I didn't release a version for 3.18 without that change. However, if you look at the commit 4eabe6db9, it's just a difference in a line of code. Open the file intellihide.js in ```~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/``` and revert that change. Then restart the shell and everything should be as before.

**Comment by saligrama** [comment]
Thank you! This works perfectly.
