### ISSUE TITLE
Intellihide is not compatible with coverflow any more

### ISSUE THREAD

**Issue by dffischer** [micheleg/dash-to-dock#303]
Commit e9301c9 broke compatibility with the [coverflow-alt-tab extension](https://github.com/dmo60/CoverflowAltTab). When Alt+Tab is pressed short enough to not bring up a switcher, everything works as expected. But when the modified switcher is used to select a window that overlaps the dock, the intellihide module no longer detects this and fails to hide the dock, occluding the window.

**Comment by micheleg** [comment]
Thanks for the bug report and sorry for the late reply. I'll have to reconsider that change.

**Comment by dffischer** [comment]
Thanks for your consideration. For the time being, simply reverting the commit before compiling the extension works just fine for me.

**Comment by micheleg** [comment]
I have reverted the commit in master [f23a7f63116] for now.

**Comment by dffischer** [comment]
Thank you. I hope you will find a better solution.

**Comment by meghprkh** [comment]
I am having this issue even after new versions of both extensions. Also please see https://github.com/dmo60/CoverflowAltTab/issues/65

**Comment by micheleg** [comment]
Hi @meghprkh ,  the issue should be "fixed" in current master, although I haven't released a new version including the fix. Can you try it?

**Comment by meghprkh** [comment]
Sorry for the delay. Yes it works! Thanks a lot

**Comment by p91paul** [comment]
Hi, Coverflow Alt-Tab maintainer here. I believe this problem could be caused by this recent change we introduced: https://github.com/dmo60/CoverflowAltTab/pull/62. CoverflowAltTab now hides dash-to-dock during its animation, and shows it again when the animation is over. However, if the dash was previously hidden, showing it is wrong.

I could add a check for this (show dash to dock only if it was previously visible), or even better you could add a method on your side (or tell me where it is if it already exists) that I would call when exiting the coverflow, which triggers a recalculation of window positions to decide if the dock should be visible or not. This solution is better than a simple check for previous state because handles also what happens if a previously minimized window becomes visible after being selected with alt-tab.

**Comment by micheleg** [comment]
Hi Paolo,

I guess the method you are looking for is something like this:
https://github.com/micheleg/dash-to-dock/blob/master/docking.js#L623

But I'm not sure I'm understanding what's  happening. How are you currently hiding/showing the dash-to-dock?

**Comment by p91paul** [comment]
I hide d.t.d. when the user presses alt-tab; otherwise it would remain visible during the alt-tab animation. Then I show it again when alt-tab is released!

The method getPanels you see modified to add the dash-to-dock panel (in the pull request I linked), is called by show and onDestroy methods of the switcher and returns a collection of panels to be hidden/shown (hidden by show, restored by onDestroy).

**Comment by micheleg** [comment]
Yes, but how are you hiding/showing it? Can you point out to me the relevant code?

**Comment by p91paul** [comment]
Oh yes sorry.

Here I hide it: https://github.com/dmo60/CoverflowAltTab/blob/master/CoverflowAltTab%40dmo60.de/switcher.js#L103

and here I show it again: https://github.com/dmo60/CoverflowAltTab/blob/master/CoverflowAltTab%40dmo60.de/switcher.js#L499
