### ISSUE TITLE
How do I know what Window is Focused?

### ISSUE THREAD

**Issue by ElectricPrism** [micheleg/dash-to-dock#327]
I can't seem to notice any visual indicator to differentiate the focused window from the unfocused windows.

This is particularly important when I have Sublime running as both root and as my user for example.

I suggest maybe a brighter different colored indicator to differentiate the focused window. Or, perhaps some sort of bound box inner radial glow or something.

Your fix is appreciated :) :+1:

**Comment by franglais125** [comment]
Hmm, I seem to have the same problem when not using the Custom theme (Gnome 3.20).
I locally reverted this patch [7afa7503bbbb20b5dd3b173015d2ef0d711d2696] and it seems to work well now.
It's like the style 'running-dots' never gets called.

**Comment by ElectricPrism** [comment]
I grabbed the latest git and tested with both "Use Built In Theme" on and off.

When set to "on" it's presently drawing a lighter grey box around the Focused Active window - so at least I can now differentiate between $sudo sublime and $sublime
![dash-to-dock-theme-bug-2016-06](https://cloud.githubusercontent.com/assets/635971/15803708/65096ffa-2aa1-11e6-93c5-311d287e723d.png)

**Comment by micheleg** [comment]
Hi,

gnome-shell by default does not show any indication of the focused window, as the dash is shown only inside the overview. I added a custom css class ```focused``` as an additional styling, which is used by the built-in theme and is accessible to third party theme authors:

https://micheleg.github.io/dash-to-dock/theming.html

Therefore what you are experiencing seems to be the expected behaviour. @franglais125 I don't see any difference in behaviour with and without commit  7afa750, would you mind explaining further?

**Comment by franglais125** [comment]
@micheleg Well, maybe it was never intended for the dash to work that way. At least in Gnome 3.14 (or before patch 7afa7503bbbb20b5dd3b173015d2ef0d711d2696) when modifying the theme one can tell which window has focus.
For newer versions of the Shell (once the patch is applied), one loses this feature. It feels like a regression for someone that is used to it, but as I said, maybe it was just a bug all along :), and not the behavior you expected.

Here are two screenshots.
**Gnome 3.14**
![screenshot from 2016-06-11 16_15_20](https://cloud.githubusercontent.com/assets/19195975/15987274/bb008d72-2ff0-11e6-985b-9a08bc965f3b.png)

**Gnome 3.20**
![screenshot from 2016-06-11 16-18-51](https://cloud.githubusercontent.com/assets/19195975/15987276/c0c8a56e-2ff0-11e6-9aeb-2949f61207a7.png)

Myself, I find it is really useful to know which window has focus, even when not using the built-in theme.

**Comment by franglais125** [comment]
One more picture. This is Gnome 3.20 once I remove that patch:

![screenshot from 2016-06-11 16-25-42](https://cloud.githubusercontent.com/assets/19195975/15987284/2ae1a540-2ff1-11e6-80b6-5073b66c05ca.png)

**Comment by micheleg** [comment]
With what settings where the screenshots above taken? 

Built-in theme on or off? Also, are you using the default gnome theme (Adwaita) or a custom one?

**Comment by franglais125** [comment]
Just to make sure it wasn't something I changed manually, I created a new user and installed the extension from extensions.gnome.org without modifications.

The only setting I changed in this test is "Show windows counter indicators", to ON. Here is result:
![screenshot from 2016-06-12 11 25 37](https://cloud.githubusercontent.com/assets/19195975/15992032/6ce8b2e0-3090-11e6-9ff1-ea63945d2c49.png)

You can see that whatever theme I use, it is modified by the css style [(stylesheet.css](https://github.com/micheleg/dash-to-dock/blob/gnome-3.14/stylesheet.css) lines 81-88):
`#dashtodockContainer.running-dots.app-well-app.focused > .overview-icon,`
`#dashtodockContainer.dashtodock .app-well-app.focused > .overview-icon {`
`    transition-duration: 250;`
`    background-gradient-start: rgba(255, 255, 255, .05);`
`    background-gradient-end: rgba(255, 255, 255, .15);`
`    background-gradient-direction: vertical;`
`    border-radius: 4px;`
`    box-shadow: inset 0px 1px 2px 0px rgba(0, 0, 0, 1);`
}`

By the way, I don't have any theme installed. So it is whatever the Debian stable default one is. I think Adwaita is the default?
Since this is a new user I created for this test, I have no other add-ons installed.

**Comment by micheleg** [comment]
It took me a while but I have finally reverted [f8c3bada09f2] the offended commit.

**Comment by franglais125** [comment]
Thanks a bunch! It really helps with identifying focus for me at least :)
