### ISSUE TITLE
Vertical, extended dock overlaps top bar (conflict with hide-top-bar)

### ISSUE THREAD

**Issue by af2005** [micheleg/dash-to-dock#334]
If the extension hide-top-bar is used and the dock is on one side of the monitor (vertical) and fully extended over the screen height, the panel overlaps the top bar when entering the gnome shell. See top left of screenshot
![image](https://cloud.githubusercontent.com/assets/10899721/16053199/08264942-3268-11e6-89f3-8d98f931279a.png)

**Comment by micheleg** [comment]
Unfortunately, it is difficult to provide complete interoperability between extensions. When I position the dock I take into account the top panel, which due to the hide-top-bar extension it is not shown. Making the various UI elements dynamically take each other into account in an efficient way would require direct control of all of them. Therefore, I can't commit to fix this issue. The extension can still be used in non-extended mode by manually limiting the maximum dock size in the settings.
