### ISSUE TITLE
Running app's position on dash moves when click if *isolate workspaces* is enabled

### ISSUE THREAD

**Issue by gapplef** [micheleg/dash-to-dock#386]
Gnome 3.18 @ Ubuntu Gnome 16.04
After enable the  **isolate workspaces** option of _show running applications_, the icon of running app which are not add to favorites will automatically move to the top of all running apps once click. The effect can be seen in the flowing picture(before and after click firefox).
There is **no** problem when **isolate workspaces** option is disabled.
![3](https://cloud.githubusercontent.com/assets/5604665/19349514/f7fa5040-9185-11e6-8f67-59600f5a24c4.png)

**Comment by franglais125** [comment]
I can confirm this issue on the 3.14 branch. I actually noticed this a long time ago, but didn't notice it only happened with the isolation.

This seems to be due to the 'restacked' signal that's added when using workspace isolation (which is necessary!). I'll try to look into this later today to see if there is a fix.

**Comment by gapplef** [comment]
I really like the workspace isolation feature. Waiting for your fix.

**Comment by franglais125** [comment]
I think I managed to solve this problem.
Here is the branch with the fix: https://github.com/franglais125/dash-to-dock/tree/fix_running_order
It's only one commit really, the second one is only to add some comments: [8d12142ee18fb378460fdb03a9230e76c2ea2d64] and [bf5ae9906e1734e8dc5b4702b3222a1bfc884313].

When studying this problem, I also found that it's not only triggered with workspace isolation, but with every `dash._redisplay()` call. For instance, adding or removing a favorite sometimes has the effect of reordering the non-favorite apps. Workspace isolation made this very obvious we call this function with every `restack` event.

@micheleg would you mind reviewing this? I just applied the fix to my Jessie and Stretch systems to test it for a few days.

@gapplef can you test this branch https://github.com/franglais125/dash-to-dock/tree/fix_running_order to see if the problem is solved for you too? (it seems fine for me so far).

Cheers!

**Comment by gapplef** [comment]
Seems the problem is solved for me, Great job!
But I still notice a small problem: when I enable or disable the  isolate workspaces option, the position of the **Dash to Dock Settings** icon(the black icon in the following picture) still changes. Everything else works fine for me.
![screenshot from 2016-10-18 12-47-05](https://cloud.githubusercontent.com/assets/5604665/19464882/73f574c2-9532-11e6-9ec5-8e773b363e84.png)

**Comment by franglais125** [comment]
@gapplef I updated the branch to fix that too! Again, do you mind testing it to make sure it fixes the problem for you?

Btw, thanks for reporting the issue :)

@micheleg @gapplef Updated branch: https://github.com/franglais125/dash-to-dock/tree/fix_running_order

**Comment by gapplef** [comment]
The issue is fixed. Everything woks fine.

Appreciate your work! Thank you!

**Comment by micheleg** [comment]
I tried to simplify the code reducing unnecessary loops: https://github.com/micheleg/dash-to-dock/tree/fix_running_order

Can you check this implementation?

**Comment by franglais125** [comment]
Thanks for checking and improving the fix!

I am running it now on 3.14 and 3.20, it seems to be fine. I'll let you know if I find any problems.

**Comment by micheleg** [comment]
I've merged the fixes in master [39041f4f902f354, 805fd6c4d7].

**Comment by franglais125** [comment]
@micheleg when testing the rebased multi-monitor branch, I found a problem introduced by [ec6446f55530585f3ba40d15ca83ab4b9911c882]. This was working fine before, but I guess the transition to 3.22 on Debian testing changed something in the Shell.

The problem is that when enabling/disabling workspace isolation, the dash is not properly updated.

Do you mind reverting that commit?

My apologies for that!

**Comment by micheleg** [comment]
I have reverted the commit [fd3c73002].  So is the problem still present and should I reopen this issue?

**Comment by franglais125** [comment]
I haven't experienced the issue with that commit reverted, so I don't think we need to reopen this. It'd be nice to hear from other people too, just to confirm.

Thanks!
