### ISSUE TITLE
local .desktop files that override system .desktop files are ignored

### ISSUE THREAD

**Issue by Taijian** [micheleg/dash-to-dock#462]
First off, I have seen #416, but this one is related but slightly different.

I installed firejail today and so thought it would be a good idea to make user-specific .desktop files for my browser to always start them with firejail (for the obvious security benefit). Testing this however, I noticed that starting the application from dash-to-dock starts the .desktop from /usr/share/applications/ not the modified one from ~/.local/share/applications/. 
This is not a GNOME bug, as disabling dash-to-dock and using the 'regular' favorites dash to start the app will use the modified .desktop (with firejail).

Steps to reproduce:

install firejail
create modified firefox.desktop in ~/.local/share/applications
hit [SUPER] and start firefox from the overview
test running jail by typing: firejail --list in terminal
close firefox and restart from dash-to-dock
test running jail by typing: firejail --list in terminal
close firefox and disable dash-to-dock
start firefox from 'vanilla' dash
test running jail by typing: firejail --list in terminal

**Comment by micheleg** [comment]
Would you mind providing me with this modified .desktop file?

**Comment by Taijian** [comment]
Here you go:

file:///home/gunnar/.local/share/applications/evolution.desktop

file:///home/gunnar/.local/share/applications/userapp-Firefox-3H8ULY.desktop

**Comment by micheleg** [comment]
Sorry, you just pasted the paths or the files :)

**Comment by Taijian** [comment]
Yeah, trying to edit ... does not like me uploading the files...

**Comment by micheleg** [comment]
Maybe if you zip them? I don't know. Otherwise just copy and paste them.

**Comment by Taijian** [comment]
OK, try here:

<script src="https://gist.github.com/Taijian/c1e009acde8d8e9bece58f72bfc87c97.js"></script>

**Comment by micheleg** [comment]
I'm not sure how this is meant to work. On my system I created the desktop file and I have a duplicated entry (I removed the NoDisplay line from your file though, otherwise it would not show up at all) in the overview when I search for firefox. I tried launching it from the overview and from the dock, and it always seems to be launching the jailed versions. Which version of gnome shell are you running? Are you sure you are using the right launcher?

**Comment by Taijian** [comment]
OK, this is rather embarrassing: It seems that I am an idiot and your extension working just fine. Please excuse my bothering you with a bogus bug report, this was a PEBKAC... :(

**Comment by eevleevs** [comment]
Possibly related. I am using global dark theme but would anyway run light-coloured Evolution. So I made the `$HOME/.local/share/applications/evolution.desktop` pasted below. Evolution runs light from Gnome applications menu and dash. If docked as a favourite it still runs dark, seemingly ignoring the local `.desktop`.

https://pastebin.com/JjBMFFc4

in particular:

`Exec=env GTK_THEME=Adwaita:light evolution %U`

**Comment by ErickTucto** [comment]
The same thing also happens to me @eevleevs ... I'm not respecting my local settings for Gtk Themes

**Comment by micheleg** [comment]
@ErickTucto Can you confirm if the beviuor is the expected on e with the extension disabled?

**Comment by jcd92** [comment]
Hi Micheleg,
I found this because I am having the same problem starting firefox with a local desktop file that sets it in Wayland mode.

Normal .desktop
Exec=/usr/lib/firefox/firefox %u

Modified local .desktop
Exec=env GDK_BACKEND=wayland /usr/lib/firefox/firefox %u

It works fine if I turn off Dash to Dock and use the favourite from  the regular dash. It only goes wrong when I re-enable Dash to Dock.

Very happy to provide any additional info as I love this extension, but really want to get Firefox working on wayland.

**Comment by jcd92** [comment]
Ah, found something interesting... it doesn't matter whether it's a local .desktop or the original in /usr/share/applications.  It doesn't inherit the GDK_BACKEND=wayland environment variable in D2D, only in the original or from Activities -> Search

**Comment by phocean** [comment]
I am having exactly the same issue with my Firefox desktop launchers.

It took me a while before suspecting the extension.

**Comment by phocean** [comment]
Could you please reopen the issue?

I even reported a bug upstream, before I realize it came from an extension:

https://gitlab.gnome.org/GNOME/gnome-shell/issues/1752#note_618955
