### ISSUE TITLE
left/right margin of windows thumbnails

### ISSUE THREAD

**Issue by dasnoopy** [micheleg/dash-to-dock#557]
Hi ,  just a little aesthetic issue noticed (app compiled from source, latest commit https://github.com/micheleg/dash-to-dock/commit/5d4029b795520e117bc6cd95b8aa185ff8e5755c)
when you have enabled the windows thumbnails , then you have more than one instance of th same app running, windows thumbnails are not centered in the popup window : left and right margins are different and probably  also top /bottom margins appears not centered (see attached images)

![left](https://user-images.githubusercontent.com/296922/29001159-739aa94a-7a81-11e7-8e97-7de45ac3b240.png)

![right](https://user-images.githubusercontent.com/296922/29001160-75799758-7a81-11e7-8fc1-fd6783549e72.png)

thanks in advance

**Comment by micheleg** [comment]
Thanks for spotting this issue. I quicly looked  into the problem and I have an half idea of how to solve it. I will try to look further into it.

Note to myself: 
problem 1: scrollbars reserve space even when not shown. A possible solution here:
https://github.com/jderose9/dash-to-panel/blob/8e4d5ab17b66210da8ac7372dfba9e8b448a3ddb/windowPreview.js#L797
https://github.com/jderose9/dash-to-panel/blob/8e4d5ab17b66210da8ac7372dfba9e8b448a3ddb/windowPreview.js#L826-L850

problem 2: preview not centered. This is due to the ornament label actor (https://git.gnome.org/browse/gnome-shell/tree/js/ui/popupMenu.js#n80). Again, a solution is to manually remove it as in here:  
https://github.com/jderose9/dash-to-panel/blob/8e4d5ab17b66210da8ac7372dfba9e8b448a3ddb/windowPreview.js#L506

However, it is not clear to me why it is a problem only for the thumbnails (some misconfigured expand/fill property?)

**Comment by micheleg** [comment]
Largely improved now [6f0e17f, 937aa72d].
