### ISSUE TITLE
Shell panel displays in GNOME 3.25.90

### ISSUE THREAD

**Issue by benjamindaines** [micheleg/dash-to-dock#564]
Installed beta release of GNOME to see what's good, and it appears that the current method of Dash to Dock hiding the default panel no longer works. 

![screenshot from 2017-08-17 13-03-28](https://user-images.githubusercontent.com/3039460/29424214-d2e350fe-834c-11e7-95c4-8f6d1224ee4b.png)

**Comment by micheleg** [comment]
Thanks for the bug report! 

Please, have a look at the the gnome-3.26 branch which I've just uploaded. https://github.com/micheleg/dash-to-dock/tree/gnome-3.26, it should works now (the bug is due to the removal of the legacyTray).

Please, let me know if you spot any other bug or inconsistency with the upcoming version of GNOME Shell. Testing is very appreciated.

**Comment by franglais125** [comment]
@micheleg you were too quick, I was preparing the same fix :)

It fixes the issue for me.

**Comment by benjamindaines** [comment]
works for me

**Comment by micheleg** [comment]
@franglais125 this was a simple fix :) Merged into master as [44ed947e87692935fbfe934acc0e9faca4ec5af3].
