### ISSUE TITLE
Double dock with GNOME 3.25.90

### ISSUE THREAD

**Issue by jbicha** [micheleg/dash-to-dock#568]
GNOME Shell 3.25.90 from GNOME3 Staging PPA
Ubuntu 17.10 Alpha
Ubuntu Dock 0.2

When I open the Activities Overview with GNOME 3.25.90, I see the built-in GNOME "dash" behind the Ubuntu Dock (I didn't see this earlier with Dash to Dock but the Ubuntu Dock has transparency by default.) Also the _Show Applications_ button at the bottom of the Ubuntu Dock doesn't do anything when clicked but the _Show Applications_ button in the GNOME dash does work.

**Comment by franglais125** [comment]
I think this is the same issue #564, which was fixed in [44ed947e87692935fbfe934acc0e9faca4ec5af3]. This will need to be included in ubuntu-dock. I read somewhere that @didrocks was doing a rebase on Monday.

The *Show Applications* button problem, might just be another symptom of the same issue. SInce the legacyTray is no more, the extension doesn't finish initializing properly, and it causes a bunch of problems. Can you test the latest version from master?

The same logic applies to #569.

**Comment by micheleg** [comment]
I have no such problem too on current GNOME upstream (jhbuild) and current master. I'm letting the Ubuntu teem manage the rebase or the ubuntu-dock branch (you might want to try to do it by yourself in the meantime).

**Comment by micheleg** [comment]
Closing this as it was solved in master  by [44ed947].

**Comment by didrocks** [comment]
Currently rebasing on master and uploading that today in artful. Thanks for the warning to you 3 :)
