### ISSUE TITLE
Possibility to show count of unread messages in dock

### ISSUE THREAD

**Issue by tommueller** [micheleg/dash-to-dock#595]
Hi,

would it be possible to show the unread count of new messages (for example for thunderbird or telegram) on the icon of the application in the dock?

Thanks
Tom

**Comment by micheleg** [comment]
That's something that was tentatively developed in the past but never finalised due to API limitations, and also somehow to try to stick with the Gnome notificatoin system. However, the Ubuntu team is working on such feature (#590). This will hopfeullly be integrated in dash-to-dock but it will only availabe in Ubuntu (and derivatives), unless the support for those API is upstreamed.

**Comment by tommueller** [comment]
@micheleg Thanks for getting back on this.

I assumed this shouldn't be too hard (as docky etc. have it), but I am not on Ubuntu, so I will get used to the fact of not having this feature anymore ;)
I love Gnome3, but still not too excited about the notification system ... maybe I'll change my mind with a bit more experience.

Thanks for the great extension!

**Comment by micheleg** [comment]
Closing as #590 was merged.
