### ISSUE TITLE
Running favorited snap application shows two icons

### ISSUE THREAD

**Issue by galgalesh** [micheleg/dash-to-dock#598]
Not sure if bug in dash-to-dock or snappy.

If you favorite a snap, the icon shows up on the Ubuntu Dock. If you click the icon, the application starts, but it creates a second (lower resolution) icon for the running application.

**steps to reproduce:**

- install atom from snap
- favorite atom
- run atom

**What I expect:**

Atom icon shows that atom is running

**What I get:**

two icons, one is running, one isn't.

![image](https://user-images.githubusercontent.com/1492981/30747162-599c8d24-9f7a-11e7-8372-d875c98a151b.png)

Bug in snappy:

https://bugs.launchpad.net/snappy/+bug/1718942

**Comment by galgalesh** [comment]
PS: @didrocks, is this the correct place for Ubuntu Dock bugs?

**Comment by didrocks** [comment]
I think you should first file the ubuntu dock bugs against the package in launchpad (to not pollute upstream dash to dash if it's not a dash to dock issue ;)), which is gnome-shell-extension-ubuntu-dock. However, your issue is purely a snap one, not the dock, so I'll this one, and let the snappy team handles the other ones about matching (it may be snappy/gnome-shell matching) :)
