### ISSUE TITLE
Brave browser creates duplicated icons when added to favorites

### ISSUE THREAD

**Issue by jacobcantele** [micheleg/dash-to-dock#602]
I'm using Brave as my default browser. Whenever I open it from the favorite in Dash-to-Dock, it creates a second duplicated icon in the dock. I believe the issue is the same as something that used to happen with Chrome:

https://github.com/micheleg/dash-to-dock/issues/215

There is a hacky workaround in there for Chrome, but I'm not sure how to apply it to Brave.

**Comment by jacobmischka** [comment]
All it takes is adding `brave` to the `StartupWMClass` prop in the .desktop file. Unfortunately, the spec doesn't allow multiple values, but in this case just `brave` on its own works for the git package you're using.

This isn't an issue with dash-to-dock, I'll push a fix to the [aur package](https://aur.archlinux.org/pkgbase/brave-git/) you're using. Please close this!

**Comment by micheleg** [comment]
Yes, this is really an upstream issue, which can be workaournd as suggested (thanks @jacobmischka). Leaving the issue open for other people to find it.

**Comment by imyxh** [comment]
Yep, happens with firefox-trunk (and krita) as well. I just made a second .desktop file in ~/.local/share/applications that specifies `StartupWMClass=Nightly` because the maintainers of the mozilla-daily ppa didn't respond to my email yet.
You can use `xprop WM_CLASS` followed by clicking on the window to find out what class the desktop file should specify.

**Comment by jacobcantele** [comment]
This issue is an upstream issue with the AUR package. Closing it.
