### ISSUE TITLE
[RFE] Allow moving the Show applications button to the upper edge

### ISSUE THREAD

**Issue by AsciiWolf** [micheleg/dash-to-dock#689]
Please, consider making it possible to move the Show applications button to the upper edge, just like it was in the Ubuntu Unity dock. Also consider making the upper position a default for Ubuntu Dock.

**Comment by AsciiWolf** [comment]
I see that there is [already a PR](https://github.com/micheleg/dash-to-dock/pull/466) adding this change.

**Comment by micheleg** [comment]
Moving the Show applications button to the upper edge has been possible since almost forever through the settings. Regarding making it the default, I honestly prefer it at the bottom which is also the position in the upstream dash, therefore I'm inclined on leaving it there (Although it could be moved to the left for horizontal orientation.)

**Comment by AsciiWolf** [comment]
@micheleg I think it should definitely be moved to the left for horizontal orientation. ;-)

**Comment by AsciiWolf** [comment]
@3v1n0 Would it be possible to move the Show applications button to the left by-default when Ubuntu Dock is at the bottom?
