### ISSUE TITLE
Dock border is not transparent if transparent Dock

### ISSUE THREAD

**Issue by dvorapa** [micheleg/dash-to-dock#695]
You can see the long gray line next to icons (dock border), which should be transparent too, if the dock transparency is set to 100 %:
![snimek z 2018-03-04 10-45-39](https://user-images.githubusercontent.com/5113916/36944376-2682e39c-1f9b-11e8-913f-46389553a92a.png)

----
Extension version: 62
Gnome Shell version: 3.26.2
Linux distribution and version: Arch Linux latest/fully updated (build 20180201)
Whether you have a multi-monitor configuration: nope
Your settings:
```$ dconf dump /org/gnome/shell/extensions/dash-to-dock/
[/]
preferred-monitor=0
shift-click-action='minimize'
shift-middle-click-action='launch'
extend-height=true
dock-fixed=true
force-straight-corner=true
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
show-windows-preview=false
show-show-apps-button=false
hot-keys=false
custom-background-color=false
custom-theme-customize-running-dots=true
apply-custom-theme=false
custom-theme-running-dots=true
unity-backlit-items=false
dock-position='LEFT'
custom-theme-shrink=true
icon-size-fixed=true
middle-click-action='launch'
background-color='#ffffff'
isolate-workspaces=true
```

**Comment by dvorapa** [comment]
You have to have the "reduced dock" option switched on

**Comment by FlanknTank** [comment]
Same problem here, but for me it only happens when the dock is reduced on the bottom on Gnome shell 3.30, ubuntu 18.10

**Comment by dvorapa** [comment]
Never occurred again

**Comment by noahdigesu** [comment]
## Issue solved
The 1px border is due to the option `shrink the dash` under the `appearance` tab.


### Easy fix
Don't shrink the dash
### More complex (but still super easy) fix
Edit the **4th line** in `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css` from `border:1px;` to `border:0px`.
That way you **can both shrink the dash and remove the border**
(It was really triggering me too so I searched a bit ahah)

Hope this helped @dvorapa ^^
