### ISSUE TITLE
Click with the touch screen opens two windows at a time

### ISSUE THREAD

**Issue by TeoColuccio** [micheleg/dash-to-dock#805]
With the dash-to-dock active, when i click with hands on my touch screen (lenovo yoga), it open two windows for any apps. With the touchpad this does not happen and also  If i disabile the extension, it works regularly too. My os is mannaro and i have all update on stable channel.

**Comment by 3v1n0** [comment]
This is now fixed for latest gnome-shell and cherry-picked to 3.28 and 3.30.

If there's interest we could fix this at extension level either for older shell versions, it can be done as explained in https://github.com/micheleg/dash-to-dock/issues/196#issuecomment-432913465

I think we can close the bug here, unless there's interest in workaround the issue at this level.
