### ISSUE TITLE
Disabling icon badge count not possible

### ISSUE THREAD

**Issue by LuFlo** [micheleg/dash-to-dock#872]
AFAIK it's not possible to disable the badge message count. Since it's not possible to disable this feature in Discord too, it is very annoying. Even if I disable all desktop notifications for Discord in Ubuntu, the numbers are still showing :(

**Comment by fbruetting** [comment]
Hi! I came here to ask if you could please deactivate these badges by default. I have a very annoying issue with Geary:

E-Mail is not an instant messaging service, and therefore it’s counterproductive to often look or even reply to new emails (there are a lot of studies about that topic). This is pretty distracting because of its red error-like color and really creates pressure, because I often have to look there and it appears to me in a way like it wants to tell me all the time “Read it! Read it! Read it!”. This may not be felt by everyone, but I like things to be clean and as I have a good sight, I (sadly) recognize those badges all the time.

So to which behavior leads that issue for me? I open Geary, mark all new mails as read (without really realizing them, because they’re E-Mails and thus in almost all cases not important at all) and continue my work. Just for that badge to disappear. I don’t care if my mails are one or three days old, and I’m pretty sure that this counts for most people out. there. So at least in my case, the impact is purely negative.

So I’d therefore like to request to deactivate that badge by default, as this also is not contained in the GNOME HIG and leads to a LOT of distraction (at least for some people). I recommend just sticking to notifications and the notification center instead by default. But at the very minimum, an option for deactivation really is necessary here.

**Comment by pvreevil** [comment]
+1
