### ISSUE TITLE
Shadow on start and end of the dock

### ISSUE THREAD

**Issue by itsrave** [micheleg/dash-to-dock#923]
I have shadow on start and end of my dock 
[https://i.imgur.com/SLd5iUd.png](Image)

**Comment by micheleg** [comment]
Can't open the image. Also, please provide some context (e.g. versions, distro, themes)

**Comment by Kruemmelkeks** [comment]
I don't know what itsrave exactly means, but maybe it's the same issue I get:
https://ibb.co/DL5j3jB

Linux: Ubuntu 19.04 (Gnome 3.32)
Extension Version: 65

The error occurs when trying to change the transparency in the appearance settings. As soon as I change it from the default value to anything else, the shadows at the end appear. All other settings are set to default values. I had to reset the extension to get rid of this bug, but whenever I change the transparency setting it will appear again.
Maybe this is fixed in version 66, but I cannot install that version (see https://github.com/micheleg/dash-to-dock/issues/938).
